name = "silent-king-5fdc"
main = "src/index.ts"
compatibility_date = "2024-03-04"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "synapse"

[[d1_databases]]
binding = "DB"
database_name = "synapse"
database_id = "8808683a-e6c3-4cf0-a1aa-8bebbf3930e6"

[vars]
EMBEDDING_DIMENSIONALITY = 1024
DEFAULT_OPENAI_EMBEDDING_MODEL = "text-embedding-3-large"