name = "silent-king-5fdc"
main = "src/index.ts"
compatibility_date = "2024-03-04"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "embeddings"

[[d1_databases]]
binding = "DB"
database_name = "index"
database_id = "e190383f-3cb2-4097-bc67-f117f629aa37"

[vars]
EMBEDDING_DIMENSIONALITY = 1024
DEFAULT_OPENAI_EMBEDDING_MODEL = "text-embedding-3-large"