name = "silent-king-5fdc"
main = "src/index.ts"
compatibility_date = "2024-03-04"

[vars]
EMBEDDING_DIMENSIONALITY = 1024
DEFAULT_OPENAI_EMBEDDING_MODEL = "text-embedding-3-large"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "synapse"
